page_width: 8.3
page_width_dimension: in
page_height: 11.7
page_height_dimension: in
one_long_page: false
page_format: custom
horizontal_margins: 0.2
horizontal_margins_dimension: in
vertical_margins: 0.2
vertical_margins_dimension: in
add_page_number: false
add_footer_source_url: false
add_pdfcrowd_logo: false
user_password: false
owner_password: false
printing_allowed: true
copying_allowed: true
modification_allowed: true
encrypt: false
page_layout: null
initial_zoom: null
full_screen: false
zoom: 100
pdf_scaling: 133
run_js: true
print_images: true
print_backgrounds: true
use_print_version: false
make_hyperlinks: true
html_zoom: 100
